openapi: "3.0.0"
info:
  version: 0.0.1
  title: virtu matching api
  description: api for the virtu applications matching microservice.
  license: 
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: Benedikt Schoeffmann
    url: https://www.crearex.net
    email: b.schoeffmann@crearex.net
servers:
  - url: https://www.crearex.net/virtu/api/v1
tags:
  - name: production
    description: All Operations pertaining to a Production   
  - name: contractor
    description: All Operations pertaining to a Contractors 
paths:
  /customer:
    $ref: resources/paths/customer/customers.yaml
  /customer/{customerId}:
    $ref: resources/paths/customer/customerById.yaml
  /operator:
    $ref: resources/paths/operator/operators.yaml
  /operator/{operatorId}:
    $ref: resources/paths/operator/operatorById.yaml    
  /operator/type/{operatorType}:
    $ref: resources/paths/operator/operatorByType.yaml


components:
  parameters:
    $ref: parameters/_index.yaml
  schemas:
    $ref: schemas/_index.yaml
  responses:
    $ref: responses/_index.yaml
