type: object
description: File Storage for the production.
properties:
  id:
    type: integer
    format: int64
  storageType:
    type: string
    enum: [S3, S3 Intelligent]
  size:
    type: number
    format: float
    description: Size in GB. 
  creationDate:
    type: string
    format: date-time
  retentionPolicy:
    type: string
    enum: [1month, userCancellation]
    


    