title: 'ProductionElement' 
type: object
properties:
  id:
    type: integer
    format: int64
  description:
    type: string
  ressource:
    $ref: "./Ressource.yaml"
  contractor:
    $ref: "./Contractor.yaml"
  additionalProperties:
    type: string
  
    