type: object
required:
  - id
  - name
  - description
  - productionOwner
  - startDate
  - endDate
properties:
  id:
    type: integer
    format: int64
  name:
    type: string
  description:  
    type: string
  startDate:
    $ref: './DateTime.yaml'
  endDate:
    $ref: './DateTime.yaml'
  productionOwner:
    $ref: './User.yaml'
  elements:
    type: array
    items:
      $ref: "./ProductionElement.yaml"
  # tasks:
  #   type: array
  #   items:  
  #     $ref: './Task.yaml'
