title: 'ProductionElement' 
type: object
properties:
  id:
    type: integer
    format: int64
  description:
    type: string
  pictureUrl:
    type: string
  ressources:
    type: array
    items:
      $ref: "./Ressource.yaml"
  contractors:
    type: array
    items:
      $ref: "./Contractor.yaml"
  additionalProperties:
    $ref: './Requisite.yaml'
  
    